apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watsonx-ai-cluster-gitops
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Howard-Luo/non-olm-cp4d-gitops-wx-ai.git
    targetRevision: main
    path: repos/watsonx-ai/cluster-scope
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
